### ISSUE TITLE
Trying 2016 general election data at the county level

### ISSUE THREAD

**Issue by restrellado** [openelections/openelections-data-id#1]
Hi, Derek! I'm taking a crack at the 2016 general election data at the county level. I'd like to do more, but I wanted to try this one and have it reviewed to make sure it's what you need before I try to scale it to do more. I'll do a PR as soon as it's ready.

**Comment by dwillis** [comment]
@restrellado Awesome, thanks!

**Comment by restrellado** [comment]
@dwillis Question for you: there are NAs in the votes field of the district 1 and district 2 candidates. Assuming this is because you can't have votes for representatives from more than one district, is it ok to remove the NAs as part of the cleaning process?

**Comment by restrellado** [comment]
Here's the pull request for this: #3.
